baseURL = 'http://gfgm.net/'
languageCode = 'en-us'
title = 'GFGM'
theme = "leagacycrown"


[menu]
 [[menu.main]]
   name = "Home"
   pre = "home"
   url = "/"
   weight = 1
 [[menu.main]]
   name = "Posts"
   pre = "pen-tool"
   url = "/posts/"
   weight = 2
 [[menu.main]]
   name = "Support"
   pre = "help-circle"
   url = "/support/"
   weight = 3
 [[menu.footer]]
   name = "Impressum"
   pre = "info"
   url = "/impressum"
   weight = 1
 [[menu.footer]]
   name = "About"
   pre = "user"
   url = "/about"
   weight = 2

  [[menu.sidebar]]
    name = "Search"
    weight = 1
  [[menu.sidebar]]
    name = "Tags"
    weight = 2
  [[menu.sidebar]]
    name = "Categories"
    weight = 3
  [[menu.sidebar]]
    name = "Archive"
    weight = 4

[permalinks]
  posts = "/:year/:month/:slug/"

[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"

[params]
 coverImage = "images/cover.jpg"
 thumbnailImage = true
 thumbnailImagePosition = "left"
 autoThumbnailImage = true
